/**
 * packager.js — Creates the final brand package zip file.
 * Produces: brand-guide.md (8-section template), brand-guide.json, brand-assets/ folder with README.
 */

import archiver from 'archiver';
import { createReadStream, existsSync } from 'fs';

// ── Render brand-guide.md following the AI Page Building template ──────────

function renderBrandGuide(job) {
  const bi = job.brandIdentity || {};
  const cs = job.colorSystem || {};
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  let md = `# ${bi.brandName || job.clientName} — Brand Guide for AI-Powered Page Building\n`;
  md += `*Generated by Impact OS on ${date}*\n`;
  md += `*Source: ${job.url}*\n\n---\n\n`;

  // Section 1: Brand Identity
  md += `## 1. BRAND IDENTITY\n\n`;
  md += `| Field | Value |\n|-------|-------|\n`;
  md += `| Brand Name | ${bi.brandName || job.clientName} |\n`;
  md += `| Tagline | ${bi.tagline || ''} |\n`;
  md += `| Industry | ${bi.industry || ''} |\n`;
  md += `| Target Audience | ${bi.targetAudience || ''} |\n`;
  md += `| Brand Personality | ${bi.brandPersonality || ''} |\n`;
  md += `| Website URL | ${job.url} |\n\n`;

  // Section 2: Color System
  md += `## 2. COLOR SYSTEM (FUNCTION-MAPPED)\n\n`;
  md += `### Primary Palette\n\n`;
  md += `| Name | Hex | Used For |\n|------|-----|----------|\n`;
  for (const c of (cs.primary || [])) {
    md += `| ${c.name} | \`${c.hex}\` | ${c.usedFor} |\n`;
  }
  md += `\n### Secondary / Utility Palette\n\n`;
  md += `| Name | Hex | Used For |\n|------|-----|----------|\n`;
  for (const c of (cs.utility || [])) {
    md += `| ${c.name} | \`${c.hex}\` | ${c.usedFor} |\n`;
  }
  md += '\n';

  // Section 3: Typography
  md += `## 3. TYPOGRAPHY\n\n`;
  md += `### Font Families\n\n`;
  md += `| Role | Font Family | Source / Import |\n|------|-------------|------------------|\n`;
  for (const f of (job.fontFamilies || [])) {
    md += `| ${f.role} | ${f.family} | ${f.source} |\n`;
  }
  md += `\n### Type Scale\n\n`;
  md += `| Element | Size | Weight | Line-H | Transform | Color Token |\n`;
  md += `|---------|------|--------|--------|-----------|-------------|\n`;
  for (const t of (job.typeScale || [])) {
    md += `| ${t.element} | ${t.size} | ${t.weight} | ${t.lineHeight} | ${t.transform} | ${t.colorToken} |\n`;
  }
  md += '\n';

  // Section 4: Component Styles
  md += `## 4. COMPONENT STYLES\n\n`;
  const btn = job.buttons || {};
  md += `### Buttons\n\n`;
  md += `| Property | Primary Button | Secondary Button |\n|----------|---------------|------------------|\n`;
  const btnPrimary = btn.primary || {};
  const btnSecondary = btn.secondary || {};
  const btnProps = ['background', 'textColor', 'border', 'borderRadius', 'padding', 'fontSize', 'fontWeight', 'hoverEffect'];
  for (const prop of btnProps) {
    const label = prop.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
    md += `| ${label} | ${btnPrimary[prop] || ''} | ${btnSecondary[prop] || ''} |\n`;
  }
  md += '\n';

  const cards = job.cards || {};
  md += `### Cards & Containers\n\n`;
  md += `| Property | Value |\n|----------|-------|\n`;
  for (const [key, val] of Object.entries(cards)) {
    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
    md += `| ${label} | ${val} |\n`;
  }
  md += '\n';

  const forms = job.formInputs || {};
  md += `### Form Inputs\n\n`;
  md += `| Property | Value |\n|----------|-------|\n`;
  for (const [key, val] of Object.entries(forms)) {
    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
    md += `| ${label} | ${val} |\n`;
  }
  md += '\n';

  // Section 5: Spacing & Layout
  md += `## 5. SPACING & LAYOUT\n\n`;
  md += `| Property | Value |\n|----------|-------|\n`;
  const spacing = job.spacing || {};
  const spacingLabels = {
    maxContentWidth: 'Max Content Width',
    sectionPadding: 'Section Padding',
    containerSidePadding: 'Container Side Padding',
    gridGap: 'Grid Gap',
    desktopColumns: 'Desktop Columns',
    mobileBreakpoint: 'Mobile Breakpoint'
  };
  for (const [key, label] of Object.entries(spacingLabels)) {
    md += `| ${label} | ${spacing[key] || ''} |\n`;
  }
  md += '\n';

  // Section 6: Decorative Effects
  md += `## 6. DECORATIVE EFFECTS\n\n`;
  if ((job.effects || []).length > 0) {
    md += `| Effect | Description / CSS |\n|--------|-------------------|\n`;
    for (const e of job.effects) {
      md += `| ${e.name} | ${e.description} |\n`;
    }
  } else {
    md += `*Clean, flat design — no decorative embellishments detected.*\n`;
  }
  md += '\n';

  // Section 7: Image Library
  md += `## 7. IMAGE LIBRARY\n\n`;
  md += `### Folder Structure\n\n`;
  md += `See the \`brand-assets/\` folder included in this package. Full inventory in \`brand-assets/README.md\`.\n\n`;

  const il = job.imageLibrary || {};
  const folderDesc = {
    logos: 'Brand logos — light, dark, icon versions',
    logos_partners: 'Partner/client logos, trust badges',
    hero: 'Hero backgrounds, textures, dividers',
    instructors: 'Founder/instructor headshots',
    instructors_team: 'Team member photos',
    testimonials: 'Customer headshot photos',
    courses: 'Product/course thumbnails',
    icons: 'UI icons, social icons, feature icons',
    lifestyle: 'Professional photography, illustrations',
    misc: 'Uncategorized assets'
  };

  md += `| Folder | Contents | Count |\n|--------|----------|-------|\n`;
  for (const [key, desc] of Object.entries(folderDesc)) {
    const count = (il[key] || []).length;
    if (count > 0) {
      md += `| /${key.replace('_', '/')}/ | ${desc} | ${count} |\n`;
    }
  }
  md += '\n';

  // Image Placement Map
  if ((job.imagePlacementMap || []).length > 0) {
    md += `### Image Placement Map\n\n`;
    md += `| Page Section | Image File | Notes |\n|-------------|------------|-------|\n`;
    for (const m of job.imagePlacementMap) {
      md += `| ${m.pageSection} | ${m.imageFile} | ${m.notes} |\n`;
    }
    md += '\n';
  }

  // Section 8: Logo Usage
  md += `## 8. LOGO USAGE\n\n`;
  if ((job.logoUsage || []).length > 0) {
    md += `| Context | Logo Version & Size |\n|---------|--------------------|\n`;
    for (const l of job.logoUsage) {
      md += `| ${l.context} | ${l.versionAndSize} |\n`;
    }
  } else {
    md += `*Logo usage rules not specified — refer to logos in brand-assets/logos/ folder.*\n`;
  }
  md += '\n';

  // Quick-start checklist
  md += `---\n\n## QUICK-START CHECKLIST\n\n`;
  md += `- [x] Section 1: Brand Identity — all fields filled\n`;
  md += `- [${(cs.primary || []).length >= 5 ? 'x' : ' '}] Section 2: Color System — every color mapped to a UI function\n`;
  md += `- [${(job.fontFamilies || []).length >= 1 ? 'x' : ' '}] Section 3: Typography — font families specified with source\n`;
  md += `- [${(job.typeScale || []).length >= 4 ? 'x' : ' '}] Section 3: Type Scale — at least H1, H2, Body, and Label defined\n`;
  md += `- [${btnPrimary.background ? 'x' : ' '}] Section 4: Button styles defined (primary + secondary)\n`;
  md += `- [${cards.background ? 'x' : ' '}] Section 4: Card/container styles defined\n`;
  md += `- [x] Section 7: Image assets organized in brand-assets/ folder\n`;
  md += `- [${(il.logos || []).length > 0 ? 'x' : ' '}] Section 7: Logo files included\n`;
  md += `- [${(job.logoUsage || []).length > 0 ? 'x' : ' '}] Section 8: Logo versions and sizes specified\n`;
  md += `\n---\n\n*One document. Every page. Perfectly on-brand.*\n`;

  return md;
}

// ── Render README.md for brand-assets folder ───────────────────────────────

function renderReadme(job) {
  const bi = job.brandIdentity || {};
  const il = job.imageLibrary || {};
  const date = new Date().toISOString().split('T')[0];

  let md = `# ${bi.brandName || job.clientName} — Brand Assets Library\n\n`;
  md += `Collected from ${job.url} on ${date}.\n\n`;

  md += `## Folder Structure\n\n`;
  md += `| Folder | Contents | Count |\n|--------|----------|-------|\n`;

  const folders = [
    ['logos', 'Brand logos (light, dark, icon versions)'],
    ['logos_partners', 'Partner and client logos, trust badges'],
    ['hero', 'Hero backgrounds, textures, section dividers'],
    ['instructors', 'Founder, instructor, speaker headshots'],
    ['instructors_team', 'Team member photos'],
    ['testimonials', 'Customer and client headshots'],
    ['courses', 'Product, course, and service thumbnails'],
    ['icons', 'UI icons, social media icons, feature icons'],
    ['lifestyle', 'Professional photography, event photos, illustrations'],
    ['misc', 'Uncategorized visual assets']
  ];

  let totalFiles = 0;
  for (const [key, desc] of folders) {
    const count = (il[key] || []).length;
    totalFiles += count;
    md += `| \`/${key.replace('_', '/')}/\` | ${desc} | ${count} |\n`;
  }
  md += '\n';

  // Key files section
  md += `## Key Files\n\n`;
  if ((il.logos || []).length > 0) {
    md += `- **Primary Logo:** \`logos/${il.logos[0].filename}\`\n`;
  }
  if ((il.hero || []).length > 0) {
    md += `- **Primary Hero:** \`hero/${il.hero[0].filename}\`\n`;
  }
  if ((il.instructors || []).length > 0) {
    md += `- **Founder/Instructor:** \`instructors/${il.instructors[0].filename}\`\n`;
  }
  md += '\n';

  md += `## Total: ${totalFiles} files\n`;

  return md;
}

// ── Build ZIP ──────────────────────────────────────────────────────────────

/**
 * Build a zip file and pipe it to a writable stream.
 * ZIP structure:
 *   {clientName}-brand/
 *   ├── brand-guide.md
 *   ├── brand-guide.json
 *   └── brand-assets/
 *       ├── logos/ (+ partners/)
 *       ├── hero/
 *       ├── instructors/ (+ team/)
 *       ├── testimonials/
 *       ├── courses/
 *       ├── icons/
 *       ├── lifestyle/
 *       ├── misc/
 *       └── README.md
 */
export function buildZip(job, outputStream) {
  return new Promise((resolve, reject) => {
    const folderName = `${job.clientName.toLowerCase().replace(/\s+/g, '-')}-brand`;
    const archive = archiver('zip', { zlib: { level: 6 } });

    archive.on('error', reject);
    archive.pipe(outputStream);
    outputStream.on('finish', resolve);
    outputStream.on('error', reject);

    // brand-guide.md
    archive.append(renderBrandGuide(job), { name: `${folderName}/brand-guide.md` });

    // brand-guide.json (structured data for programmatic use)
    const jsonData = {
      brandIdentity: job.brandIdentity,
      colorSystem: job.colorSystem,
      fontFamilies: job.fontFamilies,
      typeScale: job.typeScale,
      buttons: job.buttons,
      cards: job.cards,
      formInputs: job.formInputs,
      spacing: job.spacing,
      effects: job.effects,
      logoUsage: job.logoUsage,
      imagePlacementMap: job.imagePlacementMap,
    };
    archive.append(JSON.stringify(jsonData, null, 2), { name: `${folderName}/brand-guide.json` });

    // brand-assets/README.md
    archive.append(renderReadme(job), { name: `${folderName}/brand-assets/README.md` });

    // Map category keys to folder paths in the zip
    const categoryToZipPath = {
      logos: 'logos',
      logos_partners: 'logos/partners',
      hero: 'hero',
      instructors: 'instructors',
      instructors_team: 'instructors/team',
      testimonials: 'testimonials',
      courses: 'courses',
      icons: 'icons',
      lifestyle: 'lifestyle',
      misc: 'misc'
    };

    // Add all image assets
    const il = job.imageLibrary || {};
    for (const [category, zipFolder] of Object.entries(categoryToZipPath)) {
      for (const asset of (il[category] || [])) {
        if (asset.localPath && existsSync(asset.localPath)) {
          archive.append(createReadStream(asset.localPath), {
            name: `${folderName}/brand-assets/${zipFolder}/${asset.filename}`
          });
        }
      }
    }

    // Add uploaded assets to misc/
    for (const asset of (il.uploads || [])) {
      if (asset.localPath && existsSync(asset.localPath)) {
        archive.append(createReadStream(asset.localPath), {
          name: `${folderName}/brand-assets/misc/${asset.filename}`
        });
      }
    }

    archive.finalize();
  });
}
